/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AuthenticatedWordCounterRouteImport } from './routes/_authenticated/word-counter'
import { Route as AuthenticatedWebsiteSpeedRouteImport } from './routes/_authenticated/website-speed'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedToolHistoryRouteImport } from './routes/_authenticated/tool-history'
import { Route as AuthenticatedSiteAuditRouteImport } from './routes/_authenticated/site-audit'
import { Route as AuthenticatedSheetsRouteImport } from './routes/_authenticated/sheets'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSeoNewsRouteImport } from './routes/_authenticated/seo-news'
import { Route as AuthenticatedSchemaValidatorRouteImport } from './routes/_authenticated/schema-validator'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedResponsiveCheckRouteImport } from './routes/_authenticated/responsive-check'
import { Route as AuthenticatedRankTrackingRouteImport } from './routes/_authenticated/rank-tracking'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPreferencesRouteImport } from './routes/_authenticated/preferences'
import { Route as AuthenticatedPingRouteImport } from './routes/_authenticated/ping'
import { Route as AuthenticatedPeopleAlsoSearchRouteImport } from './routes/_authenticated/people-also-search'
import { Route as AuthenticatedPeopleAlsoAskRouteImport } from './routes/_authenticated/people-also-ask'
import { Route as AuthenticatedPendingApprovalRouteImport } from './routes/_authenticated/pending-approval'
import { Route as AuthenticatedMegaAuditRouteImport } from './routes/_authenticated/mega-audit'
import { Route as AuthenticatedLinkManagementRouteImport } from './routes/_authenticated/link-management'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedKeywordDiscoveryRouteImport } from './routes/_authenticated/keyword-discovery'
import { Route as AuthenticatedHtmlValidatorRouteImport } from './routes/_authenticated/html-validator'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedGscRouteImport } from './routes/_authenticated/gsc'
import { Route as AuthenticatedGapsRouteImport } from './routes/_authenticated/gaps'
import { Route as AuthenticatedDisavowRouteImport } from './routes/_authenticated/disavow'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedContentOptimizerRouteImport } from './routes/_authenticated/content-optimizer'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedBrokenLinksRouteImport } from './routes/_authenticated/broken-links'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as AuthenticatedBacklinkMonitorRouteImport } from './routes/_authenticated/backlink-monitor'
import { Route as AuthenticatedBacklinkCheckerRouteImport } from './routes/_authenticated/backlink-checker'
import { Route as AuthenticatedAiSearchRankRouteImport } from './routes/_authenticated/ai-search-rank'
import { Route as AuthenticatedAiSearchComparisonRouteImport } from './routes/_authenticated/ai-search-comparison'
import { Route as AuthenticatedAiPotentialRouteImport } from './routes/_authenticated/ai-potential'
import { Route as AuthenticatedAiDetectionRouteImport } from './routes/_authenticated/ai-detection'
import { Route as AuthenticatedAiCitationsRouteImport } from './routes/_authenticated/ai-citations'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin-billing'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as SharedReportTokenRouteImport } from './routes/shared/report.$token'
import { Route as AuthenticatedToolsRobotsTxtGeneratorRouteImport } from './routes/_authenticated/tools.robots-txt-generator'
import { Route as AuthenticatedSiteAuditIdRouteImport } from './routes/_authenticated/site-audit.$id'
import { Route as AuthenticatedMegaAuditIdRouteImport } from './routes/_authenticated/mega-audit.$id'
import { Route as AuthenticatedAuditNewRouteImport } from './routes/_authenticated/audit.new'
import { Route as AuthenticatedAuditBulkRouteImport } from './routes/_authenticated/audit.bulk'
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated/audit.$id'
import { Route as ApiReportsIdPdfRouteImport } from './routes/api/reports.$id.pdf'
import { Route as ApiPublicHooksRunScheduledAuditsRouteImport } from './routes/api/public/hooks/run-scheduled-audits'
import { Route as ApiPublicHooksBkashWebhookRouteImport } from './routes/api/public/hooks/bkash-webhook'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWordCounterRoute =
  AuthenticatedWordCounterRouteImport.update({
    id: '/word-counter',
    path: '/word-counter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWebsiteSpeedRoute =
  AuthenticatedWebsiteSpeedRouteImport.update({
    id: '/website-speed',
    path: '/website-speed',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolHistoryRoute =
  AuthenticatedToolHistoryRouteImport.update({
    id: '/tool-history',
    path: '/tool-history',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSiteAuditRoute = AuthenticatedSiteAuditRouteImport.update({
  id: '/site-audit',
  path: '/site-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSheetsRoute = AuthenticatedSheetsRouteImport.update({
  id: '/sheets',
  path: '/sheets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSeoNewsRoute = AuthenticatedSeoNewsRouteImport.update({
  id: '/seo-news',
  path: '/seo-news',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchemaValidatorRoute =
  AuthenticatedSchemaValidatorRouteImport.update({
    id: '/schema-validator',
    path: '/schema-validator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResponsiveCheckRoute =
  AuthenticatedResponsiveCheckRouteImport.update({
    id: '/responsive-check',
    path: '/responsive-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRankTrackingRoute =
  AuthenticatedRankTrackingRouteImport.update({
    id: '/rank-tracking',
    path: '/rank-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPreferencesRoute =
  AuthenticatedPreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPingRoute = AuthenticatedPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPeopleAlsoSearchRoute =
  AuthenticatedPeopleAlsoSearchRouteImport.update({
    id: '/people-also-search',
    path: '/people-also-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPeopleAlsoAskRoute =
  AuthenticatedPeopleAlsoAskRouteImport.update({
    id: '/people-also-ask',
    path: '/people-also-ask',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPendingApprovalRoute =
  AuthenticatedPendingApprovalRouteImport.update({
    id: '/pending-approval',
    path: '/pending-approval',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMegaAuditRoute = AuthenticatedMegaAuditRouteImport.update({
  id: '/mega-audit',
  path: '/mega-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLinkManagementRoute =
  AuthenticatedLinkManagementRouteImport.update({
    id: '/link-management',
    path: '/link-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordDiscoveryRoute =
  AuthenticatedKeywordDiscoveryRouteImport.update({
    id: '/keyword-discovery',
    path: '/keyword-discovery',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHtmlValidatorRoute =
  AuthenticatedHtmlValidatorRouteImport.update({
    id: '/html-validator',
    path: '/html-validator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGscRoute = AuthenticatedGscRouteImport.update({
  id: '/gsc',
  path: '/gsc',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGapsRoute = AuthenticatedGapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDisavowRoute = AuthenticatedDisavowRouteImport.update({
  id: '/disavow',
  path: '/disavow',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentOptimizerRoute =
  AuthenticatedContentOptimizerRouteImport.update({
    id: '/content-optimizer',
    path: '/content-optimizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrokenLinksRoute =
  AuthenticatedBrokenLinksRouteImport.update({
    id: '/broken-links',
    path: '/broken-links',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBacklinkMonitorRoute =
  AuthenticatedBacklinkMonitorRouteImport.update({
    id: '/backlink-monitor',
    path: '/backlink-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBacklinkCheckerRoute =
  AuthenticatedBacklinkCheckerRouteImport.update({
    id: '/backlink-checker',
    path: '/backlink-checker',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSearchRankRoute =
  AuthenticatedAiSearchRankRouteImport.update({
    id: '/ai-search-rank',
    path: '/ai-search-rank',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiSearchComparisonRoute =
  AuthenticatedAiSearchComparisonRouteImport.update({
    id: '/ai-search-comparison',
    path: '/ai-search-comparison',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiPotentialRoute =
  AuthenticatedAiPotentialRouteImport.update({
    id: '/ai-potential',
    path: '/ai-potential',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiDetectionRoute =
  AuthenticatedAiDetectionRouteImport.update({
    id: '/ai-detection',
    path: '/ai-detection',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCitationsRoute =
  AuthenticatedAiCitationsRouteImport.update({
    id: '/ai-citations',
    path: '/ai-citations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/admin-billing',
    path: '/admin-billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const SharedReportTokenRoute = SharedReportTokenRouteImport.update({
  id: '/shared/report/$token',
  path: '/shared/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToolsRobotsTxtGeneratorRoute =
  AuthenticatedToolsRobotsTxtGeneratorRouteImport.update({
    id: '/robots-txt-generator',
    path: '/robots-txt-generator',
    getParentRoute: () => AuthenticatedToolsRoute,
  } as any)
const AuthenticatedSiteAuditIdRoute =
  AuthenticatedSiteAuditIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSiteAuditRoute,
  } as any)
const AuthenticatedMegaAuditIdRoute =
  AuthenticatedMegaAuditIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMegaAuditRoute,
  } as any)
const AuthenticatedAuditNewRoute = AuthenticatedAuditNewRouteImport.update({
  id: '/audit/new',
  path: '/audit/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditBulkRoute = AuthenticatedAuditBulkRouteImport.update({
  id: '/audit/bulk',
  path: '/audit/bulk',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiReportsIdPdfRoute = ApiReportsIdPdfRouteImport.update({
  id: '/api/reports/$id/pdf',
  path: '/api/reports/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRunScheduledAuditsRoute =
  ApiPublicHooksRunScheduledAuditsRouteImport.update({
    id: '/api/public/hooks/run-scheduled-audits',
    path: '/api/public/hooks/run-scheduled-audits',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksBkashWebhookRoute =
  ApiPublicHooksBkashWebhookRouteImport.update({
    id: '/api/public/hooks/bkash-webhook',
    path: '/api/public/hooks/bkash-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-billing': typeof AuthenticatedAdminBillingRoute
  '/ai-citations': typeof AuthenticatedAiCitationsRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/ai-potential': typeof AuthenticatedAiPotentialRoute
  '/ai-search-comparison': typeof AuthenticatedAiSearchComparisonRoute
  '/ai-search-rank': typeof AuthenticatedAiSearchRankRoute
  '/backlink-checker': typeof AuthenticatedBacklinkCheckerRoute
  '/backlink-monitor': typeof AuthenticatedBacklinkMonitorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/broken-links': typeof AuthenticatedBrokenLinksRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disavow': typeof AuthenticatedDisavowRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/gsc': typeof AuthenticatedGscRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/html-validator': typeof AuthenticatedHtmlValidatorRoute
  '/keyword-discovery': typeof AuthenticatedKeywordDiscoveryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/link-management': typeof AuthenticatedLinkManagementRoute
  '/mega-audit': typeof AuthenticatedMegaAuditRouteWithChildren
  '/pending-approval': typeof AuthenticatedPendingApprovalRoute
  '/people-also-ask': typeof AuthenticatedPeopleAlsoAskRoute
  '/people-also-search': typeof AuthenticatedPeopleAlsoSearchRoute
  '/ping': typeof AuthenticatedPingRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/responsive-check': typeof AuthenticatedResponsiveCheckRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/schema-validator': typeof AuthenticatedSchemaValidatorRoute
  '/seo-news': typeof AuthenticatedSeoNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/site-audit': typeof AuthenticatedSiteAuditRouteWithChildren
  '/tool-history': typeof AuthenticatedToolHistoryRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/website-speed': typeof AuthenticatedWebsiteSpeedRoute
  '/word-counter': typeof AuthenticatedWordCounterRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/audit/bulk': typeof AuthenticatedAuditBulkRoute
  '/audit/new': typeof AuthenticatedAuditNewRoute
  '/mega-audit/$id': typeof AuthenticatedMegaAuditIdRoute
  '/site-audit/$id': typeof AuthenticatedSiteAuditIdRoute
  '/tools/robots-txt-generator': typeof AuthenticatedToolsRobotsTxtGeneratorRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/api/public/hooks/bkash-webhook': typeof ApiPublicHooksBkashWebhookRoute
  '/api/public/hooks/run-scheduled-audits': typeof ApiPublicHooksRunScheduledAuditsRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/admin-billing': typeof AuthenticatedAdminBillingRoute
  '/ai-citations': typeof AuthenticatedAiCitationsRoute
  '/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/ai-potential': typeof AuthenticatedAiPotentialRoute
  '/ai-search-comparison': typeof AuthenticatedAiSearchComparisonRoute
  '/ai-search-rank': typeof AuthenticatedAiSearchRankRoute
  '/backlink-checker': typeof AuthenticatedBacklinkCheckerRoute
  '/backlink-monitor': typeof AuthenticatedBacklinkMonitorRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/broken-links': typeof AuthenticatedBrokenLinksRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/disavow': typeof AuthenticatedDisavowRoute
  '/gaps': typeof AuthenticatedGapsRoute
  '/gsc': typeof AuthenticatedGscRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/html-validator': typeof AuthenticatedHtmlValidatorRoute
  '/keyword-discovery': typeof AuthenticatedKeywordDiscoveryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/link-management': typeof AuthenticatedLinkManagementRoute
  '/mega-audit': typeof AuthenticatedMegaAuditRouteWithChildren
  '/pending-approval': typeof AuthenticatedPendingApprovalRoute
  '/people-also-ask': typeof AuthenticatedPeopleAlsoAskRoute
  '/people-also-search': typeof AuthenticatedPeopleAlsoSearchRoute
  '/ping': typeof AuthenticatedPingRoute
  '/preferences': typeof AuthenticatedPreferencesRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/responsive-check': typeof AuthenticatedResponsiveCheckRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/schema-validator': typeof AuthenticatedSchemaValidatorRoute
  '/seo-news': typeof AuthenticatedSeoNewsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/sheets': typeof AuthenticatedSheetsRoute
  '/site-audit': typeof AuthenticatedSiteAuditRouteWithChildren
  '/tool-history': typeof AuthenticatedToolHistoryRoute
  '/tools': typeof AuthenticatedToolsRouteWithChildren
  '/website-speed': typeof AuthenticatedWebsiteSpeedRoute
  '/word-counter': typeof AuthenticatedWordCounterRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/audit/bulk': typeof AuthenticatedAuditBulkRoute
  '/audit/new': typeof AuthenticatedAuditNewRoute
  '/mega-audit/$id': typeof AuthenticatedMegaAuditIdRoute
  '/site-audit/$id': typeof AuthenticatedSiteAuditIdRoute
  '/tools/robots-txt-generator': typeof AuthenticatedToolsRobotsTxtGeneratorRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/api/public/hooks/bkash-webhook': typeof ApiPublicHooksBkashWebhookRoute
  '/api/public/hooks/run-scheduled-audits': typeof ApiPublicHooksRunScheduledAuditsRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/admin-billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/ai-citations': typeof AuthenticatedAiCitationsRoute
  '/_authenticated/ai-detection': typeof AuthenticatedAiDetectionRoute
  '/_authenticated/ai-potential': typeof AuthenticatedAiPotentialRoute
  '/_authenticated/ai-search-comparison': typeof AuthenticatedAiSearchComparisonRoute
  '/_authenticated/ai-search-rank': typeof AuthenticatedAiSearchRankRoute
  '/_authenticated/backlink-checker': typeof AuthenticatedBacklinkCheckerRoute
  '/_authenticated/backlink-monitor': typeof AuthenticatedBacklinkMonitorRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/broken-links': typeof AuthenticatedBrokenLinksRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/disavow': typeof AuthenticatedDisavowRoute
  '/_authenticated/gaps': typeof AuthenticatedGapsRoute
  '/_authenticated/gsc': typeof AuthenticatedGscRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/html-validator': typeof AuthenticatedHtmlValidatorRoute
  '/_authenticated/keyword-discovery': typeof AuthenticatedKeywordDiscoveryRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/link-management': typeof AuthenticatedLinkManagementRoute
  '/_authenticated/mega-audit': typeof AuthenticatedMegaAuditRouteWithChildren
  '/_authenticated/pending-approval': typeof AuthenticatedPendingApprovalRoute
  '/_authenticated/people-also-ask': typeof AuthenticatedPeopleAlsoAskRoute
  '/_authenticated/people-also-search': typeof AuthenticatedPeopleAlsoSearchRoute
  '/_authenticated/ping': typeof AuthenticatedPingRoute
  '/_authenticated/preferences': typeof AuthenticatedPreferencesRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/_authenticated/responsive-check': typeof AuthenticatedResponsiveCheckRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/_authenticated/schema-validator': typeof AuthenticatedSchemaValidatorRoute
  '/_authenticated/seo-news': typeof AuthenticatedSeoNewsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/sheets': typeof AuthenticatedSheetsRoute
  '/_authenticated/site-audit': typeof AuthenticatedSiteAuditRouteWithChildren
  '/_authenticated/tool-history': typeof AuthenticatedToolHistoryRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRouteWithChildren
  '/_authenticated/website-speed': typeof AuthenticatedWebsiteSpeedRoute
  '/_authenticated/word-counter': typeof AuthenticatedWordCounterRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute
  '/_authenticated/audit/bulk': typeof AuthenticatedAuditBulkRoute
  '/_authenticated/audit/new': typeof AuthenticatedAuditNewRoute
  '/_authenticated/mega-audit/$id': typeof AuthenticatedMegaAuditIdRoute
  '/_authenticated/site-audit/$id': typeof AuthenticatedSiteAuditIdRoute
  '/_authenticated/tools/robots-txt-generator': typeof AuthenticatedToolsRobotsTxtGeneratorRoute
  '/shared/report/$token': typeof SharedReportTokenRoute
  '/api/public/hooks/bkash-webhook': typeof ApiPublicHooksBkashWebhookRoute
  '/api/public/hooks/run-scheduled-audits': typeof ApiPublicHooksRunScheduledAuditsRoute
  '/api/reports/$id/pdf': typeof ApiReportsIdPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-billing'
    | '/ai-citations'
    | '/ai-detection'
    | '/ai-potential'
    | '/ai-search-comparison'
    | '/ai-search-rank'
    | '/backlink-checker'
    | '/backlink-monitor'
    | '/billing'
    | '/broken-links'
    | '/calendar'
    | '/checklist'
    | '/competitors'
    | '/content-optimizer'
    | '/dashboard'
    | '/disavow'
    | '/gaps'
    | '/gsc'
    | '/history'
    | '/html-validator'
    | '/keyword-discovery'
    | '/keywords'
    | '/link-management'
    | '/mega-audit'
    | '/pending-approval'
    | '/people-also-ask'
    | '/people-also-search'
    | '/ping'
    | '/preferences'
    | '/profile'
    | '/projects'
    | '/rank-tracking'
    | '/responsive-check'
    | '/scheduled'
    | '/schema-validator'
    | '/seo-news'
    | '/settings'
    | '/sheets'
    | '/site-audit'
    | '/tool-history'
    | '/tools'
    | '/website-speed'
    | '/word-counter'
    | '/checkout/$slug'
    | '/audit/$id'
    | '/audit/bulk'
    | '/audit/new'
    | '/mega-audit/$id'
    | '/site-audit/$id'
    | '/tools/robots-txt-generator'
    | '/shared/report/$token'
    | '/api/public/hooks/bkash-webhook'
    | '/api/public/hooks/run-scheduled-audits'
    | '/api/reports/$id/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/admin-billing'
    | '/ai-citations'
    | '/ai-detection'
    | '/ai-potential'
    | '/ai-search-comparison'
    | '/ai-search-rank'
    | '/backlink-checker'
    | '/backlink-monitor'
    | '/billing'
    | '/broken-links'
    | '/calendar'
    | '/checklist'
    | '/competitors'
    | '/content-optimizer'
    | '/dashboard'
    | '/disavow'
    | '/gaps'
    | '/gsc'
    | '/history'
    | '/html-validator'
    | '/keyword-discovery'
    | '/keywords'
    | '/link-management'
    | '/mega-audit'
    | '/pending-approval'
    | '/people-also-ask'
    | '/people-also-search'
    | '/ping'
    | '/preferences'
    | '/profile'
    | '/projects'
    | '/rank-tracking'
    | '/responsive-check'
    | '/scheduled'
    | '/schema-validator'
    | '/seo-news'
    | '/settings'
    | '/sheets'
    | '/site-audit'
    | '/tool-history'
    | '/tools'
    | '/website-speed'
    | '/word-counter'
    | '/checkout/$slug'
    | '/audit/$id'
    | '/audit/bulk'
    | '/audit/new'
    | '/mega-audit/$id'
    | '/site-audit/$id'
    | '/tools/robots-txt-generator'
    | '/shared/report/$token'
    | '/api/public/hooks/bkash-webhook'
    | '/api/public/hooks/run-scheduled-audits'
    | '/api/reports/$id/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/admin-billing'
    | '/_authenticated/ai-citations'
    | '/_authenticated/ai-detection'
    | '/_authenticated/ai-potential'
    | '/_authenticated/ai-search-comparison'
    | '/_authenticated/ai-search-rank'
    | '/_authenticated/backlink-checker'
    | '/_authenticated/backlink-monitor'
    | '/_authenticated/billing'
    | '/_authenticated/broken-links'
    | '/_authenticated/calendar'
    | '/_authenticated/checklist'
    | '/_authenticated/competitors'
    | '/_authenticated/content-optimizer'
    | '/_authenticated/dashboard'
    | '/_authenticated/disavow'
    | '/_authenticated/gaps'
    | '/_authenticated/gsc'
    | '/_authenticated/history'
    | '/_authenticated/html-validator'
    | '/_authenticated/keyword-discovery'
    | '/_authenticated/keywords'
    | '/_authenticated/link-management'
    | '/_authenticated/mega-audit'
    | '/_authenticated/pending-approval'
    | '/_authenticated/people-also-ask'
    | '/_authenticated/people-also-search'
    | '/_authenticated/ping'
    | '/_authenticated/preferences'
    | '/_authenticated/profile'
    | '/_authenticated/projects'
    | '/_authenticated/rank-tracking'
    | '/_authenticated/responsive-check'
    | '/_authenticated/scheduled'
    | '/_authenticated/schema-validator'
    | '/_authenticated/seo-news'
    | '/_authenticated/settings'
    | '/_authenticated/sheets'
    | '/_authenticated/site-audit'
    | '/_authenticated/tool-history'
    | '/_authenticated/tools'
    | '/_authenticated/website-speed'
    | '/_authenticated/word-counter'
    | '/checkout/$slug'
    | '/_authenticated/audit/$id'
    | '/_authenticated/audit/bulk'
    | '/_authenticated/audit/new'
    | '/_authenticated/mega-audit/$id'
    | '/_authenticated/site-audit/$id'
    | '/_authenticated/tools/robots-txt-generator'
    | '/shared/report/$token'
    | '/api/public/hooks/bkash-webhook'
    | '/api/public/hooks/run-scheduled-audits'
    | '/api/reports/$id/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  SharedReportTokenRoute: typeof SharedReportTokenRoute
  ApiPublicHooksBkashWebhookRoute: typeof ApiPublicHooksBkashWebhookRoute
  ApiPublicHooksRunScheduledAuditsRoute: typeof ApiPublicHooksRunScheduledAuditsRoute
  ApiReportsIdPdfRoute: typeof ApiReportsIdPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/word-counter': {
      id: '/_authenticated/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof AuthenticatedWordCounterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/website-speed': {
      id: '/_authenticated/website-speed'
      path: '/website-speed'
      fullPath: '/website-speed'
      preLoaderRoute: typeof AuthenticatedWebsiteSpeedRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tool-history': {
      id: '/_authenticated/tool-history'
      path: '/tool-history'
      fullPath: '/tool-history'
      preLoaderRoute: typeof AuthenticatedToolHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/site-audit': {
      id: '/_authenticated/site-audit'
      path: '/site-audit'
      fullPath: '/site-audit'
      preLoaderRoute: typeof AuthenticatedSiteAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sheets': {
      id: '/_authenticated/sheets'
      path: '/sheets'
      fullPath: '/sheets'
      preLoaderRoute: typeof AuthenticatedSheetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/seo-news': {
      id: '/_authenticated/seo-news'
      path: '/seo-news'
      fullPath: '/seo-news'
      preLoaderRoute: typeof AuthenticatedSeoNewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schema-validator': {
      id: '/_authenticated/schema-validator'
      path: '/schema-validator'
      fullPath: '/schema-validator'
      preLoaderRoute: typeof AuthenticatedSchemaValidatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/responsive-check': {
      id: '/_authenticated/responsive-check'
      path: '/responsive-check'
      fullPath: '/responsive-check'
      preLoaderRoute: typeof AuthenticatedResponsiveCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rank-tracking': {
      id: '/_authenticated/rank-tracking'
      path: '/rank-tracking'
      fullPath: '/rank-tracking'
      preLoaderRoute: typeof AuthenticatedRankTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/preferences': {
      id: '/_authenticated/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof AuthenticatedPreferencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ping': {
      id: '/_authenticated/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof AuthenticatedPingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people-also-search': {
      id: '/_authenticated/people-also-search'
      path: '/people-also-search'
      fullPath: '/people-also-search'
      preLoaderRoute: typeof AuthenticatedPeopleAlsoSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/people-also-ask': {
      id: '/_authenticated/people-also-ask'
      path: '/people-also-ask'
      fullPath: '/people-also-ask'
      preLoaderRoute: typeof AuthenticatedPeopleAlsoAskRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pending-approval': {
      id: '/_authenticated/pending-approval'
      path: '/pending-approval'
      fullPath: '/pending-approval'
      preLoaderRoute: typeof AuthenticatedPendingApprovalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mega-audit': {
      id: '/_authenticated/mega-audit'
      path: '/mega-audit'
      fullPath: '/mega-audit'
      preLoaderRoute: typeof AuthenticatedMegaAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/link-management': {
      id: '/_authenticated/link-management'
      path: '/link-management'
      fullPath: '/link-management'
      preLoaderRoute: typeof AuthenticatedLinkManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keyword-discovery': {
      id: '/_authenticated/keyword-discovery'
      path: '/keyword-discovery'
      fullPath: '/keyword-discovery'
      preLoaderRoute: typeof AuthenticatedKeywordDiscoveryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/html-validator': {
      id: '/_authenticated/html-validator'
      path: '/html-validator'
      fullPath: '/html-validator'
      preLoaderRoute: typeof AuthenticatedHtmlValidatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gsc': {
      id: '/_authenticated/gsc'
      path: '/gsc'
      fullPath: '/gsc'
      preLoaderRoute: typeof AuthenticatedGscRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gaps': {
      id: '/_authenticated/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof AuthenticatedGapsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/disavow': {
      id: '/_authenticated/disavow'
      path: '/disavow'
      fullPath: '/disavow'
      preLoaderRoute: typeof AuthenticatedDisavowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-optimizer': {
      id: '/_authenticated/content-optimizer'
      path: '/content-optimizer'
      fullPath: '/content-optimizer'
      preLoaderRoute: typeof AuthenticatedContentOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/broken-links': {
      id: '/_authenticated/broken-links'
      path: '/broken-links'
      fullPath: '/broken-links'
      preLoaderRoute: typeof AuthenticatedBrokenLinksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlink-monitor': {
      id: '/_authenticated/backlink-monitor'
      path: '/backlink-monitor'
      fullPath: '/backlink-monitor'
      preLoaderRoute: typeof AuthenticatedBacklinkMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/backlink-checker': {
      id: '/_authenticated/backlink-checker'
      path: '/backlink-checker'
      fullPath: '/backlink-checker'
      preLoaderRoute: typeof AuthenticatedBacklinkCheckerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-search-rank': {
      id: '/_authenticated/ai-search-rank'
      path: '/ai-search-rank'
      fullPath: '/ai-search-rank'
      preLoaderRoute: typeof AuthenticatedAiSearchRankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-search-comparison': {
      id: '/_authenticated/ai-search-comparison'
      path: '/ai-search-comparison'
      fullPath: '/ai-search-comparison'
      preLoaderRoute: typeof AuthenticatedAiSearchComparisonRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-potential': {
      id: '/_authenticated/ai-potential'
      path: '/ai-potential'
      fullPath: '/ai-potential'
      preLoaderRoute: typeof AuthenticatedAiPotentialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-detection': {
      id: '/_authenticated/ai-detection'
      path: '/ai-detection'
      fullPath: '/ai-detection'
      preLoaderRoute: typeof AuthenticatedAiDetectionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-citations': {
      id: '/_authenticated/ai-citations'
      path: '/ai-citations'
      fullPath: '/ai-citations'
      preLoaderRoute: typeof AuthenticatedAiCitationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin-billing': {
      id: '/_authenticated/admin-billing'
      path: '/admin-billing'
      fullPath: '/admin-billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/shared/report/$token': {
      id: '/shared/report/$token'
      path: '/shared/report/$token'
      fullPath: '/shared/report/$token'
      preLoaderRoute: typeof SharedReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tools/robots-txt-generator': {
      id: '/_authenticated/tools/robots-txt-generator'
      path: '/robots-txt-generator'
      fullPath: '/tools/robots-txt-generator'
      preLoaderRoute: typeof AuthenticatedToolsRobotsTxtGeneratorRouteImport
      parentRoute: typeof AuthenticatedToolsRoute
    }
    '/_authenticated/site-audit/$id': {
      id: '/_authenticated/site-audit/$id'
      path: '/$id'
      fullPath: '/site-audit/$id'
      preLoaderRoute: typeof AuthenticatedSiteAuditIdRouteImport
      parentRoute: typeof AuthenticatedSiteAuditRoute
    }
    '/_authenticated/mega-audit/$id': {
      id: '/_authenticated/mega-audit/$id'
      path: '/$id'
      fullPath: '/mega-audit/$id'
      preLoaderRoute: typeof AuthenticatedMegaAuditIdRouteImport
      parentRoute: typeof AuthenticatedMegaAuditRoute
    }
    '/_authenticated/audit/new': {
      id: '/_authenticated/audit/new'
      path: '/audit/new'
      fullPath: '/audit/new'
      preLoaderRoute: typeof AuthenticatedAuditNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/bulk': {
      id: '/_authenticated/audit/bulk'
      path: '/audit/bulk'
      fullPath: '/audit/bulk'
      preLoaderRoute: typeof AuthenticatedAuditBulkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/reports/$id/pdf': {
      id: '/api/reports/$id/pdf'
      path: '/api/reports/$id/pdf'
      fullPath: '/api/reports/$id/pdf'
      preLoaderRoute: typeof ApiReportsIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/run-scheduled-audits': {
      id: '/api/public/hooks/run-scheduled-audits'
      path: '/api/public/hooks/run-scheduled-audits'
      fullPath: '/api/public/hooks/run-scheduled-audits'
      preLoaderRoute: typeof ApiPublicHooksRunScheduledAuditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/bkash-webhook': {
      id: '/api/public/hooks/bkash-webhook'
      path: '/api/public/hooks/bkash-webhook'
      fullPath: '/api/public/hooks/bkash-webhook'
      preLoaderRoute: typeof ApiPublicHooksBkashWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedMegaAuditRouteChildren {
  AuthenticatedMegaAuditIdRoute: typeof AuthenticatedMegaAuditIdRoute
}

const AuthenticatedMegaAuditRouteChildren: AuthenticatedMegaAuditRouteChildren =
  {
    AuthenticatedMegaAuditIdRoute: AuthenticatedMegaAuditIdRoute,
  }

const AuthenticatedMegaAuditRouteWithChildren =
  AuthenticatedMegaAuditRoute._addFileChildren(
    AuthenticatedMegaAuditRouteChildren,
  )

interface AuthenticatedSiteAuditRouteChildren {
  AuthenticatedSiteAuditIdRoute: typeof AuthenticatedSiteAuditIdRoute
}

const AuthenticatedSiteAuditRouteChildren: AuthenticatedSiteAuditRouteChildren =
  {
    AuthenticatedSiteAuditIdRoute: AuthenticatedSiteAuditIdRoute,
  }

const AuthenticatedSiteAuditRouteWithChildren =
  AuthenticatedSiteAuditRoute._addFileChildren(
    AuthenticatedSiteAuditRouteChildren,
  )

interface AuthenticatedToolsRouteChildren {
  AuthenticatedToolsRobotsTxtGeneratorRoute: typeof AuthenticatedToolsRobotsTxtGeneratorRoute
}

const AuthenticatedToolsRouteChildren: AuthenticatedToolsRouteChildren = {
  AuthenticatedToolsRobotsTxtGeneratorRoute:
    AuthenticatedToolsRobotsTxtGeneratorRoute,
}

const AuthenticatedToolsRouteWithChildren =
  AuthenticatedToolsRoute._addFileChildren(AuthenticatedToolsRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAiCitationsRoute: typeof AuthenticatedAiCitationsRoute
  AuthenticatedAiDetectionRoute: typeof AuthenticatedAiDetectionRoute
  AuthenticatedAiPotentialRoute: typeof AuthenticatedAiPotentialRoute
  AuthenticatedAiSearchComparisonRoute: typeof AuthenticatedAiSearchComparisonRoute
  AuthenticatedAiSearchRankRoute: typeof AuthenticatedAiSearchRankRoute
  AuthenticatedBacklinkCheckerRoute: typeof AuthenticatedBacklinkCheckerRoute
  AuthenticatedBacklinkMonitorRoute: typeof AuthenticatedBacklinkMonitorRoute
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedBrokenLinksRoute: typeof AuthenticatedBrokenLinksRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedContentOptimizerRoute: typeof AuthenticatedContentOptimizerRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDisavowRoute: typeof AuthenticatedDisavowRoute
  AuthenticatedGapsRoute: typeof AuthenticatedGapsRoute
  AuthenticatedGscRoute: typeof AuthenticatedGscRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHtmlValidatorRoute: typeof AuthenticatedHtmlValidatorRoute
  AuthenticatedKeywordDiscoveryRoute: typeof AuthenticatedKeywordDiscoveryRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedLinkManagementRoute: typeof AuthenticatedLinkManagementRoute
  AuthenticatedMegaAuditRoute: typeof AuthenticatedMegaAuditRouteWithChildren
  AuthenticatedPendingApprovalRoute: typeof AuthenticatedPendingApprovalRoute
  AuthenticatedPeopleAlsoAskRoute: typeof AuthenticatedPeopleAlsoAskRoute
  AuthenticatedPeopleAlsoSearchRoute: typeof AuthenticatedPeopleAlsoSearchRoute
  AuthenticatedPingRoute: typeof AuthenticatedPingRoute
  AuthenticatedPreferencesRoute: typeof AuthenticatedPreferencesRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRankTrackingRoute: typeof AuthenticatedRankTrackingRoute
  AuthenticatedResponsiveCheckRoute: typeof AuthenticatedResponsiveCheckRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedSchemaValidatorRoute: typeof AuthenticatedSchemaValidatorRoute
  AuthenticatedSeoNewsRoute: typeof AuthenticatedSeoNewsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSheetsRoute: typeof AuthenticatedSheetsRoute
  AuthenticatedSiteAuditRoute: typeof AuthenticatedSiteAuditRouteWithChildren
  AuthenticatedToolHistoryRoute: typeof AuthenticatedToolHistoryRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRouteWithChildren
  AuthenticatedWebsiteSpeedRoute: typeof AuthenticatedWebsiteSpeedRoute
  AuthenticatedWordCounterRoute: typeof AuthenticatedWordCounterRoute
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute
  AuthenticatedAuditBulkRoute: typeof AuthenticatedAuditBulkRoute
  AuthenticatedAuditNewRoute: typeof AuthenticatedAuditNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAiCitationsRoute: AuthenticatedAiCitationsRoute,
  AuthenticatedAiDetectionRoute: AuthenticatedAiDetectionRoute,
  AuthenticatedAiPotentialRoute: AuthenticatedAiPotentialRoute,
  AuthenticatedAiSearchComparisonRoute: AuthenticatedAiSearchComparisonRoute,
  AuthenticatedAiSearchRankRoute: AuthenticatedAiSearchRankRoute,
  AuthenticatedBacklinkCheckerRoute: AuthenticatedBacklinkCheckerRoute,
  AuthenticatedBacklinkMonitorRoute: AuthenticatedBacklinkMonitorRoute,
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedBrokenLinksRoute: AuthenticatedBrokenLinksRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedContentOptimizerRoute: AuthenticatedContentOptimizerRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDisavowRoute: AuthenticatedDisavowRoute,
  AuthenticatedGapsRoute: AuthenticatedGapsRoute,
  AuthenticatedGscRoute: AuthenticatedGscRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHtmlValidatorRoute: AuthenticatedHtmlValidatorRoute,
  AuthenticatedKeywordDiscoveryRoute: AuthenticatedKeywordDiscoveryRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedLinkManagementRoute: AuthenticatedLinkManagementRoute,
  AuthenticatedMegaAuditRoute: AuthenticatedMegaAuditRouteWithChildren,
  AuthenticatedPendingApprovalRoute: AuthenticatedPendingApprovalRoute,
  AuthenticatedPeopleAlsoAskRoute: AuthenticatedPeopleAlsoAskRoute,
  AuthenticatedPeopleAlsoSearchRoute: AuthenticatedPeopleAlsoSearchRoute,
  AuthenticatedPingRoute: AuthenticatedPingRoute,
  AuthenticatedPreferencesRoute: AuthenticatedPreferencesRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRankTrackingRoute: AuthenticatedRankTrackingRoute,
  AuthenticatedResponsiveCheckRoute: AuthenticatedResponsiveCheckRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedSchemaValidatorRoute: AuthenticatedSchemaValidatorRoute,
  AuthenticatedSeoNewsRoute: AuthenticatedSeoNewsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSheetsRoute: AuthenticatedSheetsRoute,
  AuthenticatedSiteAuditRoute: AuthenticatedSiteAuditRouteWithChildren,
  AuthenticatedToolHistoryRoute: AuthenticatedToolHistoryRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRouteWithChildren,
  AuthenticatedWebsiteSpeedRoute: AuthenticatedWebsiteSpeedRoute,
  AuthenticatedWordCounterRoute: AuthenticatedWordCounterRoute,
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
  AuthenticatedAuditBulkRoute: AuthenticatedAuditBulkRoute,
  AuthenticatedAuditNewRoute: AuthenticatedAuditNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  SharedReportTokenRoute: SharedReportTokenRoute,
  ApiPublicHooksBkashWebhookRoute: ApiPublicHooksBkashWebhookRoute,
  ApiPublicHooksRunScheduledAuditsRoute: ApiPublicHooksRunScheduledAuditsRoute,
  ApiReportsIdPdfRoute: ApiReportsIdPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
