/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWordCounterRouteImport } from './routes/_authenticated/word-counter'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedScheduledRouteImport } from './routes/_authenticated/scheduled'
import { Route as AuthenticatedRankTrackingRouteImport } from './routes/_authenticated/rank-tracking'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPingRouteImport } from './routes/_authenticated/ping'
import { Route as AuthenticatedKeywordsRouteImport } from './routes/_authenticated/keywords'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrawlerRouteImport } from './routes/_authenticated/crawler'
import { Route as AuthenticatedContentOptimizerRouteImport } from './routes/_authenticated/content-optimizer'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedChecklistRouteImport } from './routes/_authenticated/checklist'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAiVisibilityRouteImport } from './routes/_authenticated/ai-visibility'
import { Route as AuthenticatedCrawlerIdRouteImport } from './routes/_authenticated/crawler.$id'
import { Route as AuthenticatedAuditNewRouteImport } from './routes/_authenticated/audit.new'
import { Route as AuthenticatedAuditIdRouteImport } from './routes/_authenticated/audit.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWordCounterRoute =
  AuthenticatedWordCounterRouteImport.update({
    id: '/word-counter',
    path: '/word-counter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduledRoute = AuthenticatedScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankTrackingRoute =
  AuthenticatedRankTrackingRouteImport.update({
    id: '/rank-tracking',
    path: '/rank-tracking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPingRoute = AuthenticatedPingRouteImport.update({
  id: '/ping',
  path: '/ping',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKeywordsRoute = AuthenticatedKeywordsRouteImport.update({
  id: '/keywords',
  path: '/keywords',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrawlerRoute = AuthenticatedCrawlerRouteImport.update({
  id: '/crawler',
  path: '/crawler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentOptimizerRoute =
  AuthenticatedContentOptimizerRouteImport.update({
    id: '/content-optimizer',
    path: '/content-optimizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistRoute = AuthenticatedChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiVisibilityRoute =
  AuthenticatedAiVisibilityRouteImport.update({
    id: '/ai-visibility',
    path: '/ai-visibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCrawlerIdRoute = AuthenticatedCrawlerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrawlerRoute,
} as any)
const AuthenticatedAuditNewRoute = AuthenticatedAuditNewRouteImport.update({
  id: '/audit/new',
  path: '/audit/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditIdRoute = AuthenticatedAuditIdRouteImport.update({
  id: '/audit/$id',
  path: '/audit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/crawler': typeof AuthenticatedCrawlerRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/ping': typeof AuthenticatedPingRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/word-counter': typeof AuthenticatedWordCounterRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/audit/new': typeof AuthenticatedAuditNewRoute
  '/crawler/$id': typeof AuthenticatedCrawlerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/checklist': typeof AuthenticatedChecklistRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/crawler': typeof AuthenticatedCrawlerRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/keywords': typeof AuthenticatedKeywordsRoute
  '/ping': typeof AuthenticatedPingRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/scheduled': typeof AuthenticatedScheduledRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/word-counter': typeof AuthenticatedWordCounterRoute
  '/audit/$id': typeof AuthenticatedAuditIdRoute
  '/audit/new': typeof AuthenticatedAuditNewRoute
  '/crawler/$id': typeof AuthenticatedCrawlerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/ai-visibility': typeof AuthenticatedAiVisibilityRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/checklist': typeof AuthenticatedChecklistRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/content-optimizer': typeof AuthenticatedContentOptimizerRoute
  '/_authenticated/crawler': typeof AuthenticatedCrawlerRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/keywords': typeof AuthenticatedKeywordsRoute
  '/_authenticated/ping': typeof AuthenticatedPingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/rank-tracking': typeof AuthenticatedRankTrackingRoute
  '/_authenticated/scheduled': typeof AuthenticatedScheduledRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/word-counter': typeof AuthenticatedWordCounterRoute
  '/_authenticated/audit/$id': typeof AuthenticatedAuditIdRoute
  '/_authenticated/audit/new': typeof AuthenticatedAuditNewRoute
  '/_authenticated/crawler/$id': typeof AuthenticatedCrawlerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-visibility'
    | '/calendar'
    | '/checklist'
    | '/competitors'
    | '/content-optimizer'
    | '/crawler'
    | '/dashboard'
    | '/history'
    | '/keywords'
    | '/ping'
    | '/projects'
    | '/rank-tracking'
    | '/scheduled'
    | '/settings'
    | '/tools'
    | '/word-counter'
    | '/audit/$id'
    | '/audit/new'
    | '/crawler/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/ai-visibility'
    | '/calendar'
    | '/checklist'
    | '/competitors'
    | '/content-optimizer'
    | '/crawler'
    | '/dashboard'
    | '/history'
    | '/keywords'
    | '/ping'
    | '/projects'
    | '/rank-tracking'
    | '/scheduled'
    | '/settings'
    | '/tools'
    | '/word-counter'
    | '/audit/$id'
    | '/audit/new'
    | '/crawler/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/ai-visibility'
    | '/_authenticated/calendar'
    | '/_authenticated/checklist'
    | '/_authenticated/competitors'
    | '/_authenticated/content-optimizer'
    | '/_authenticated/crawler'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/keywords'
    | '/_authenticated/ping'
    | '/_authenticated/projects'
    | '/_authenticated/rank-tracking'
    | '/_authenticated/scheduled'
    | '/_authenticated/settings'
    | '/_authenticated/tools'
    | '/_authenticated/word-counter'
    | '/_authenticated/audit/$id'
    | '/_authenticated/audit/new'
    | '/_authenticated/crawler/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/word-counter': {
      id: '/_authenticated/word-counter'
      path: '/word-counter'
      fullPath: '/word-counter'
      preLoaderRoute: typeof AuthenticatedWordCounterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduled': {
      id: '/_authenticated/scheduled'
      path: '/scheduled'
      fullPath: '/scheduled'
      preLoaderRoute: typeof AuthenticatedScheduledRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rank-tracking': {
      id: '/_authenticated/rank-tracking'
      path: '/rank-tracking'
      fullPath: '/rank-tracking'
      preLoaderRoute: typeof AuthenticatedRankTrackingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ping': {
      id: '/_authenticated/ping'
      path: '/ping'
      fullPath: '/ping'
      preLoaderRoute: typeof AuthenticatedPingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/keywords': {
      id: '/_authenticated/keywords'
      path: '/keywords'
      fullPath: '/keywords'
      preLoaderRoute: typeof AuthenticatedKeywordsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crawler': {
      id: '/_authenticated/crawler'
      path: '/crawler'
      fullPath: '/crawler'
      preLoaderRoute: typeof AuthenticatedCrawlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-optimizer': {
      id: '/_authenticated/content-optimizer'
      path: '/content-optimizer'
      fullPath: '/content-optimizer'
      preLoaderRoute: typeof AuthenticatedContentOptimizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklist': {
      id: '/_authenticated/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthenticatedChecklistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-visibility': {
      id: '/_authenticated/ai-visibility'
      path: '/ai-visibility'
      fullPath: '/ai-visibility'
      preLoaderRoute: typeof AuthenticatedAiVisibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crawler/$id': {
      id: '/_authenticated/crawler/$id'
      path: '/$id'
      fullPath: '/crawler/$id'
      preLoaderRoute: typeof AuthenticatedCrawlerIdRouteImport
      parentRoute: typeof AuthenticatedCrawlerRoute
    }
    '/_authenticated/audit/new': {
      id: '/_authenticated/audit/new'
      path: '/audit/new'
      fullPath: '/audit/new'
      preLoaderRoute: typeof AuthenticatedAuditNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit/$id': {
      id: '/_authenticated/audit/$id'
      path: '/audit/$id'
      fullPath: '/audit/$id'
      preLoaderRoute: typeof AuthenticatedAuditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedCrawlerRouteChildren {
  AuthenticatedCrawlerIdRoute: typeof AuthenticatedCrawlerIdRoute
}

const AuthenticatedCrawlerRouteChildren: AuthenticatedCrawlerRouteChildren = {
  AuthenticatedCrawlerIdRoute: AuthenticatedCrawlerIdRoute,
}

const AuthenticatedCrawlerRouteWithChildren =
  AuthenticatedCrawlerRoute._addFileChildren(AuthenticatedCrawlerRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiVisibilityRoute: typeof AuthenticatedAiVisibilityRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedChecklistRoute: typeof AuthenticatedChecklistRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedContentOptimizerRoute: typeof AuthenticatedContentOptimizerRoute
  AuthenticatedCrawlerRoute: typeof AuthenticatedCrawlerRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedKeywordsRoute: typeof AuthenticatedKeywordsRoute
  AuthenticatedPingRoute: typeof AuthenticatedPingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRankTrackingRoute: typeof AuthenticatedRankTrackingRoute
  AuthenticatedScheduledRoute: typeof AuthenticatedScheduledRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedWordCounterRoute: typeof AuthenticatedWordCounterRoute
  AuthenticatedAuditIdRoute: typeof AuthenticatedAuditIdRoute
  AuthenticatedAuditNewRoute: typeof AuthenticatedAuditNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiVisibilityRoute: AuthenticatedAiVisibilityRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedChecklistRoute: AuthenticatedChecklistRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedContentOptimizerRoute: AuthenticatedContentOptimizerRoute,
  AuthenticatedCrawlerRoute: AuthenticatedCrawlerRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedKeywordsRoute: AuthenticatedKeywordsRoute,
  AuthenticatedPingRoute: AuthenticatedPingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRankTrackingRoute: AuthenticatedRankTrackingRoute,
  AuthenticatedScheduledRoute: AuthenticatedScheduledRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedWordCounterRoute: AuthenticatedWordCounterRoute,
  AuthenticatedAuditIdRoute: AuthenticatedAuditIdRoute,
  AuthenticatedAuditNewRoute: AuthenticatedAuditNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
